import { and, eq, sql } from "drizzle-orm";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { planMembers, raidPlans } from "@/db/schema";

async function database() { const {getDb}=await import("@/db"); return getDb(); }
async function view(db:Awaited<ReturnType<typeof database>>,plan:typeof raidPlans.$inferSelect,currentUserId?:string){const members=await db.select().from(planMembers).where(eq(planMembers.planId,plan.id));return{map:plan.map,selectedTaskIds:JSON.parse(plan.selectedTaskIds),routeTaskIds:JSON.parse(plan.routeTaskIds),checklistState:JSON.parse(plan.checklistState),assignments:JSON.parse(plan.assignments),shareId:plan.shareId,revision:plan.revision,updatedAt:plan.updatedAt,ownerUserId:plan.userId,currentUserId:currentUserId??null,members:[{userId:plan.userId,displayName:plan.ownerName,role:"LEADER",ready:plan.ownerReady,lastSeenAt:plan.updatedAt},...members]}}

export async function GET(request:Request){const url=new URL(request.url);const shareId=url.searchParams.get("share");if(shareId){const user=await getChatGPTUser();const db=await database();const [plan]=await db.select().from(raidPlans).where(eq(raidPlans.shareId,shareId)).limit(1);return plan?Response.json({plan:await view(db,plan,user?.userId)}):Response.json({error:"Plan not found"},{status:404})}const user=await getChatGPTUser();if(!user)return Response.json({error:"Authentication required"},{status:401});const map=url.searchParams.get("map");if(!map)return Response.json({error:"map is required"},{status:400});const db=await database();const [plan]=await db.select().from(raidPlans).where(and(eq(raidPlans.userId,user.userId),eq(raidPlans.map,map))).limit(1);return Response.json({plan:plan?await view(db,plan,user.userId):null})}

export async function PUT(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"Authentication required"},{status:401});const body=await request.json() as {map?:string;selectedTaskIds?:unknown;routeTaskIds?:unknown;checklistState?:unknown;assignments?:unknown;shareId?:string;revision?:number};if(!body.map||!Array.isArray(body.selectedTaskIds)||!Array.isArray(body.routeTaskIds))return Response.json({error:"Invalid plan"},{status:400});const selected=body.selectedTaskIds.filter((id):id is string=>typeof id==="string").slice(0,200);const route=body.routeTaskIds.filter((id):id is string=>typeof id==="string"&&selected.includes(id)).slice(0,200);const checklistState=body.checklistState&&typeof body.checklistState==="object"?body.checklistState:{};const assignments=body.assignments&&typeof body.assignments==="object"?body.assignments:{};const db=await database();const now=new Date().toISOString();let plan:typeof raidPlans.$inferSelect|undefined;if(body.shareId){[plan]=await db.select().from(raidPlans).where(eq(raidPlans.shareId,body.shareId)).limit(1);if(!plan)return Response.json({error:"Plan not found"},{status:404});if(plan.userId!==user.userId){const [member]=await db.select().from(planMembers).where(and(eq(planMembers.planId,plan.id),eq(planMembers.userId,user.userId))).limit(1);if(!member)return Response.json({error:"Join the squad before editing"},{status:403})}if(typeof body.revision==="number"&&body.revision!==plan.revision)return Response.json({error:"Plan changed",plan:await view(db,plan)},{status:409});await db.update(raidPlans).set({selectedTaskIds:JSON.stringify(selected),routeTaskIds:JSON.stringify(route),checklistState:JSON.stringify(checklistState),assignments:JSON.stringify(assignments),updatedAt:now,revision:sql`${raidPlans.revision} + 1`}).where(eq(raidPlans.id,plan.id))}else{const id=`${user.userId}:${body.map}`;const newShareId=crypto.randomUUID().replaceAll("-","").slice(0,16);await db.insert(raidPlans).values({id,userId:user.userId,ownerName:user.displayName,map:body.map,selectedTaskIds:JSON.stringify(selected),routeTaskIds:JSON.stringify(route),checklistState:JSON.stringify(checklistState),assignments:JSON.stringify(assignments),shareId:newShareId,updatedAt:now}).onConflictDoUpdate({target:raidPlans.id,set:{ownerName:user.displayName,selectedTaskIds:JSON.stringify(selected),routeTaskIds:JSON.stringify(route),checklistState:JSON.stringify(checklistState),assignments:JSON.stringify(assignments),updatedAt:now,revision:sql`${raidPlans.revision} + 1`}});[plan]=await db.select().from(raidPlans).where(eq(raidPlans.id,id)).limit(1)}[plan]=await db.select().from(raidPlans).where(eq(raidPlans.id,plan!.id)).limit(1);return Response.json({plan:await view(db,plan!)})}
