"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import { boundsFor, floorFor, hazardWeightedDistance, objectivePoint, projectPoint, worldPoint, type WorldPoint } from "@/lib/planner/projection.mjs";
import { buildChecklist, type ChecklistItem } from "@/lib/planner/checklist.mjs";
import { isRaidCandidate, isTaskLocked } from "@/lib/planner/progress.mjs";
import { buildPartyDashboard, type PartyProgressMember } from "@/lib/planner/party.mjs";

type ApiObjective = { id:string; description:string; type:string; count:number|null; coordinateStatus:"verify"|"unmapped"|"verified"; mapScope:"specific"|"multiple"|"any"|"none";maps:{id:string;name:string}[];possibleLocations?:unknown[];zones?:unknown[];items?:unknown[];requiredKeys?:unknown[];markerItem?:unknown;usingWeapon?:unknown[];wearing?:unknown[];foundInRaid?:boolean;optional?:boolean };
type ApiTask = { id:string; name:string; minPlayerLevel:number; prerequisiteTaskIds:string[];trader:{id:string;name:string}|null; objectives:ApiObjective[] };
type ApiMap={spawns:Array<{position:unknown;zoneName?:string}>;extracts:Array<{id:string;name:string;position:unknown;faction?:string;switches?:string[]}>;locks:Array<{id:string;lockType:string;key?:string;needsPower?:boolean;position:unknown}>;hazards:Array<{id:string;hazardType:string;name?:string;position:unknown}>};
type ApiPayload={data:ApiTask[];map:ApiMap|null;meta:{fetchedAt?:string}};
type MarkerMeta={keyId?:string;needsPower?:boolean;faction?:string;conditional?:boolean};
type SourceMarker={id:string;name:string;point:WorldPoint;meta?:MarkerMeta};
type Task = { id:string; sourceTaskId:string;title:string; trader:string; objective:string; zone:string; x:number; y:number; world:WorldPoint|null;floor:"B1"|"GROUND"|"UPPER";status:"READY"|"UNMAPPED"|"VERIFY"; color:string; selected:boolean;requirements:{minPlayerLevel:number;prerequisiteTaskIds:string[];objectives:ApiObjective[]} };
type TacticalMarker={id:string;name:string;x:number;y:number;floor:"B1"|"GROUND"|"UPPER";world:WorldPoint;meta?:MarkerMeta};
type PlayerProfile={faction:"pmc"|"scav";playerLevel:number;keyIds:string[];allowPowered:boolean;allowConditionalExtracts:boolean};
type SquadMember = {userId?:string;displayName:string;role:string;ready:boolean;lastSeenAt?:string};
type StoredPlan = { map:string; selectedTaskIds:string[]; routeTaskIds:string[];checklistState:Record<string,boolean>;assignments:Record<string,string>;taskOwners:Record<string,string[]>;shareId:string;revision:number;members:SquadMember[];ownerUserId:string;currentUserId:string|null };

const initialTasks: Task[] = [
  { id:"demo-1",sourceTaskId:"demo-1",title:"Checking",trader:"Prapor",objective:"Machinery keyを回収し、Bronze pocket watchを確保",zone:"Customs",x:42,y:37,world:null,floor:"GROUND",status:"READY",color:"#d7ff45",selected:true,requirements:{minPlayerLevel:1,prerequisiteTaskIds:[],objectives:[]} },
  { id:"demo-2",sourceTaskId:"demo-2",title:"Delivery from the Past",trader:"Prapor",objective:"Customs officeでsecure caseを回収",zone:"Customs",x:17,y:55,world:null,floor:"GROUND",status:"READY",color:"#ffb547",selected:true,requirements:{minPlayerLevel:1,prerequisiteTaskIds:[],objectives:[]} },
  { id:"demo-3",sourceTaskId:"demo-3",title:"The Extortionist",trader:"Skier",objective:"Unknown keyでmessengerの荷物を回収",zone:"Customs",x:63,y:65,world:null,floor:"GROUND",status:"VERIFY",color:"#7dd8ff",selected:true,requirements:{minPlayerLevel:1,prerequisiteTaskIds:[],objectives:[]} },
];

const maps = ["Customs","Factory","Woods","Shoreline","Interchange","Reserve","Lighthouse","Streets of Tarkov","Ground Zero","The Lab"];
const mapAssets:Record<string,string>={Customs:"/maps/Customs.svg",Factory:"/maps/Factory.svg",Woods:"/maps/Woods.svg",Shoreline:"/maps/Shoreline.svg",Interchange:"/maps/Interchange.svg",Reserve:"/maps/Reserve.svg",Lighthouse:"/maps/Lighthouse.svg","Streets of Tarkov":"/maps/StreetsOfTarkov.svg","Ground Zero":"/maps/GroundZero.svg","The Lab":"/maps/Labs.svg",Terminal:"/maps/Terminal.svg"};
const colors = ["#d7ff45","#ffb547","#7dd8ff","#f47458","#c6a7ff","#7fffc1"];
const taskFilterLabels={all:"すべて",available:"受注可能",active:"進行中",completed:"完了",locked:"未解放"} as const;
const taskProgressLabels={available:"受注可能",active:"進行中",completed:"完了"} as const;
const floorLabels={ALL:"全階層",B1:"地下1階",GROUND:"地上階",UPPER:"上階"} as const;
const requirementLabel=(status:string)=>({READY:"準備済み",MISSING:"不足",IN_RAID:"レイド内",AVAILABLE:"利用可能",UNMAPPED:"座標未登録"}[status.replace(" ","_")]??status);
function position(id:string,index:number) { let hash=0; for (const char of id) hash=(hash*31+char.charCodeAt(0))>>>0; return {x:12+(hash%73),y:18+((hash>>>8)%65),color:colors[index%colors.length]}; }
function savedIds(key:string) { try { const value=JSON.parse(localStorage.getItem(key)??"[]"); return new Set<string>(Array.isArray(value)?value:[]); } catch { return new Set<string>(); } }
function sharedIds() { try { return new Set(decodeURIComponent(window.location.hash.replace(/^#tasks=/,"" )).split(",").filter(Boolean)); } catch { return new Set<string>(); } }

const initialSquad:SquadMember[] = [
  { displayName:"GO825",role:"LEADER",ready:true },
  { displayName:"KUMA",role:"ASSAULT",ready:true },
  { displayName:"NOVA",role:"SUPPORT",ready:false },
];

function Icon({ name }: { name:"grid"|"target"|"map"|"users"|"settings"|"plus"|"route"|"share" }) {
  const paths = {
    grid:"M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z",
    target:"M12 3a9 9 0 1 0 9 9M12 7a5 5 0 1 0 5 5M12 10a2 2 0 1 0 2 2M12 2v4M22 12h-4",
    map:"m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Zm6-3v15m6-12v15",
    users:"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75",
    settings:"M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7ZM19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1V21H9.6v-.09A1.7 1.7 0 0 0 8.5 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1-.4H3V9.6h.09A1.7 1.7 0 0 0 4.6 8.5a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1V3h4v.09A1.7 1.7 0 0 0 15.5 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.13.37.35.71.6 1 .28.29.64.42 1 .4h.09v4H21a1.7 1.7 0 0 0-1.6.6Z",
    plus:"M12 5v14M5 12h14",route:"M6 19a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm12-8a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM8.6 14.5c2-4.5 4.2-5.1 6.7-5.7M18 13v7m0 0-3-3m3 3 3-3",
    share:"M18 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM6 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm12 7a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM8.6 10.5l6.8-4M8.6 13.5l6.8 4",
  };
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]} /></svg>;
}

export default function Home() {
  const [tasks,setTasks] = useState(initialTasks);
  const [map,setMap] = useState("Customs");
  const [query,setQuery] = useState("");
  const [loading,setLoading] = useState(true);
  const [error,setError] = useState("");
  const [updatedAt,setUpdatedAt] = useState("");
  const [saved,setSaved] = useState(false);
  const [shareId,setShareId] = useState("");
  const [syncMode,setSyncMode] = useState<"LOCAL"|"CLOUD"|"SHARED">("LOCAL");
  const [syncReady,setSyncReady] = useState(false);
  const [revision,setRevision] = useState(0);
  const revisionRef=useRef(0);
  const applyingRemote=useRef(false);
  const [canEdit,setCanEdit] = useState(true);
  const [squad,setSquad] = useState(initialSquad);
  const [ownerUserId,setOwnerUserId] = useState("");
  const [currentUserId,setCurrentUserId] = useState("");
  const [conflict,setConflict] = useState<StoredPlan|null>(null);
  const [floor,setFloor] = useState<"ALL"|"B1"|"GROUND"|"UPPER">("ALL");
  const [markers,setMarkers] = useState<{spawns:TacticalMarker[];extracts:TacticalMarker[]}>({spawns:[],extracts:[]});
  const [hazards,setHazards] = useState<TacticalMarker[]>([]);
  const [locks,setLocks] = useState<TacticalMarker[]>([]);
  const [spawnId,setSpawnId] = useState("");
  const [extractId,setExtractId] = useState("");
  const [profile,setProfile] = useState<PlayerProfile>({faction:"pmc",playerLevel:1,keyIds:[],allowPowered:false,allowConditionalExtracts:false});
  const [profileReady,setProfileReady] = useState(false);
  const [checklistState,setChecklistState] = useState<Record<string,boolean>>({});
  const [assignments,setAssignments] = useState<Record<string,string>>({});
  const [taskOwners,setTaskOwners] = useState<Record<string,string[]>>({});
  const [activeTask,setActiveTask] = useState<Task|null>(null);
  const [view,setView] = useState({zoom:1,x:0,y:0});
  const [activeNav,setActiveNav] = useState("My tasks");
  const [gameMode,setGameMode] = useState<"regular"|"pve">("regular");
  const [taskCatalog,setTaskCatalog] = useState<ApiTask[]>([]);
  const [taskStates,setTaskStates] = useState<Record<string,"available"|"active"|"completed">>({});
  const [objectiveStates,setObjectiveStates] = useState<Record<string,"pending"|"in_progress"|"completed"|"handover">>({});
  const [progressReady,setProgressReady] = useState(false);
  const [taskFilter,setTaskFilter] = useState<"all"|"available"|"active"|"completed"|"locked">("all");
  const [partyProgress,setPartyProgress] = useState<PartyProgressMember[]>([]);
  const pendingPartyObjectives=useRef(new Set<string>());
  const [showWelcome,setShowWelcome] = useState(false);
  const [deleteConfirm,setDeleteConfirm] = useState("");
  const [settingsNotice,setSettingsNotice] = useState("");
  const [copied,setCopied] = useState(false);
  const [mode,setMode] = useState<"PLAN"|"LIVE">("PLAN");
  const mapAsset=mapAssets[map];
  const selected = useMemo(() => tasks.filter((task) => task.selected&&isRaidCandidate({sourceTaskId:task.sourceTaskId,objectiveId:task.requirements.objectives[0]?.id??""},taskStates,objectiveStates)),[tasks,taskStates,objectiveStates]);
  const checklist=useMemo(()=>buildChecklist(selected.map((task)=>({id:task.id,minPlayerLevel:task.requirements.minPlayerLevel,objectives:task.requirements.objectives})),profile) as ChecklistItem[],[selected,profile]);
  const completedChecklist=checklist.filter((item)=>checklistState[item.id]).length;
  const squadReadiness=useMemo(()=>squad.map((member)=>{const memberId=member.userId??member.displayName;const assigned=checklist.filter((item)=>assignments[item.id]===memberId);return {...member,total:assigned.length,done:assigned.filter((item)=>checklistState[item.id]).length}}),[squad,checklist,assignments,checklistState]);
  const currentMember=squad.find((member)=>member.userId===currentUserId);
  const isOwner=Boolean(currentUserId&&currentUserId===ownerUserId);
  const extractAvailable=(marker:TacticalMarker)=>(!marker.meta?.faction||marker.meta.faction===profile.faction||marker.meta.faction==="both")&&(!marker.meta?.conditional||profile.allowConditionalExtracts);
  const lockAvailable=(marker:TacticalMarker)=>(!marker.meta?.keyId||profile.keyIds.includes(marker.meta.keyId))&&(!marker.meta?.needsPower||profile.allowPowered);
  const chosenSpawn=markers.spawns.find((marker)=>marker.id===spawnId)??null;
  const chosenExtract=markers.extracts.find((marker)=>marker.id===extractId&&extractAvailable(marker))??null;
  const taskLocked=(task:{id:string;minPlayerLevel:number;prerequisiteTaskIds:string[]})=>isTaskLocked(task,profile.playerLevel,taskStates);
  const raidCandidates=useMemo(()=>tasks.filter((task)=>isRaidCandidate({sourceTaskId:task.sourceTaskId,objectiveId:task.requirements.objectives[0]?.id??""},taskStates,objectiveStates)),[tasks,taskStates,objectiveStates]);
  const visibleTasks = useMemo(() => { const term=query.trim().toLowerCase(); return term ? raidCandidates.filter((task) => `${task.title} ${task.trader} ${task.objective}`.toLowerCase().includes(term)) : raidCandidates; },[raidCandidates,query]);
  const filteredCatalog=useMemo(()=>taskCatalog.filter((task)=>{const locked=isTaskLocked(task,profile.playerLevel,taskStates);const state=taskStates[task.id]??"available";return taskFilter==="all"||(taskFilter==="locked"?locked:!locked&&state===taskFilter)}),[taskCatalog,taskStates,taskFilter,profile.playerLevel]);
  const partyDashboard=useMemo(()=>buildPartyDashboard(taskCatalog,partyProgress),[taskCatalog,partyProgress]);
  const taskColor=(task:Task)=>{const item=checklist.find((entry)=>entry.taskId===task.id&&assignments[entry.id]);const assigned=item?assignments[item.id]:"";const index=squad.findIndex((member)=>(member.userId??member.displayName)===assigned);return index>=0?colors[index%colors.length]:task.color};
  const taskOwnerNames=(taskId:string)=>(taskOwners[taskId]??[]).map((id)=>id==="local-owner"?"LOCAL OWNER":squad.find((member)=>member.userId===id)?.displayName??id).join(", ")||"未割り当て";
  const toggleTask = (id:string) => {const target=tasks.find((item)=>item.id===id);if(!target||taskLocked({id:target.sourceTaskId,minPlayerLevel:target.requirements.minPlayerLevel,prerequisiteTaskIds:target.requirements.prerequisiteTaskIds}))return;if(!target.selected){const memberId=currentUserId||"local-owner";setTaskOwners((owners)=>({...owners,[id]:Array.from(new Set([...(owners[id]??[]),memberId]))}))}setTasks((items)=>items.map((item)=>item.id===id?{...item,selected:!item.selected}:item))};
  const setTaskProgress=(task:ApiTask,state:"available"|"active"|"completed")=>{setTaskStates((current)=>({...current,[task.id]:state}));if(state==="completed")setObjectiveStates((current)=>({...current,...Object.fromEntries(task.objectives.map((objective)=>[objective.id,"completed" as const]))}));if(state!=="active")setTasks((items)=>items.map((item)=>item.sourceTaskId===task.id?{...item,selected:false}:item))};
  const createPartyPlan=(recommendation:{map:string;objectiveIds:string[]})=>{if(recommendation.map==="Any map")return;pendingPartyObjectives.current=new Set(recommendation.objectiveIds);setSyncReady(false);setLoading(true);setMap(recommendation.map);setActiveNav("Raid plan")};
  const exportAccount=async()=>{const response=await fetch("/api/account");if(response.status===401){window.location.href="/signin-with-chatgpt?return_to=%2F";return}if(!response.ok){setSettingsNotice("エクスポートに失敗しました");return}const blob=await response.blob(),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="tarkov-raid-planner-data.json";anchor.click();URL.revokeObjectURL(url);setSettingsNotice("データをエクスポートしました")};
  const deleteAccount=async()=>{if(deleteConfirm!=="DELETE")return;const response=await fetch("/api/account",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation:deleteConfirm})});if(response.status===401){window.location.href="/signin-with-chatgpt?return_to=%2F";return}if(response.ok){for(const key of Object.keys(localStorage))if(key.startsWith("trp-"))localStorage.removeItem(key);setTaskStates({});setObjectiveStates({});setDeleteConfirm("");setSettingsNotice("クラウドと端末のデータを削除しました")}else setSettingsNotice("削除に失敗しました")};
  const clearLocal=()=>{for(const key of Object.keys(localStorage))if(key.startsWith("trp-"))localStorage.removeItem(key);setSettingsNotice("この端末の保存データを削除しました")};
  const share = async () => {
    const url=new URL(window.location.href); url.hash="";
    if(shareId){url.search="";url.searchParams.set("share",shareId)}else{url.searchParams.set("map",map);url.hash=`tasks=${encodeURIComponent(selected.map((task)=>task.id).join(","))}`}
    window.history.replaceState(null,"",url); await navigator.clipboard?.writeText(url.toString()); setCopied(true); window.setTimeout(() => setCopied(false),1800);
  };
  const newPlan = () => { setTasks((items)=>items.map((task)=>({...task,selected:false}))); setChecklistState({});setAssignments({});setTaskOwners({});setQuery(""); window.history.replaceState(null,"",window.location.pathname); };
  const moveTask = (id:string,direction:-1|1) => setTasks((items) => {
    const route=items.filter((task)=>task.selected); const from=route.findIndex((task)=>task.id===id); const to=from+direction; if (from<0||to<0||to>=route.length) return items;
    [route[from],route[to]]=[route[to],route[from]]; const positions=items.map((task,index)=>task.selected?index:-1).filter((index)=>index>=0); const next=[...items]; positions.forEach((position,index)=>{next[position]=route[index]}); return next;
  });
  const optimizeRoute = () => setTasks((items) => {
    const pending=[...items.filter((task)=>task.selected)]; if (pending.length<2) return items; const route:Task[]=[];let current=chosenSpawn?.world??pending[0].world;
    while (pending.length) { let best=0; for(let index=1;index<pending.length;index++){ const cost=(task:Task)=>current&&task.world?hazardWeightedDistance(current,task.world,hazards.map((hazard)=>hazard.world)):(task.x-(route.at(-1)?.x??0))**2+(task.y-(route.at(-1)?.y??0))**2; if(cost(pending[index])<cost(pending[best])) best=index; } const next=pending.splice(best,1)[0];route.push(next);current=next.world??current; }
    const positions=items.map((task,index)=>task.selected?index:-1).filter((index)=>index>=0); const next=[...items]; positions.forEach((position,index)=>{next[position]=route[index]}); return next;
  });

  useEffect(() => {
    const controller = new AbortController();
    fetch(`/api/tarkov/tasks?lang=ja&mode=${gameMode}&map=${encodeURIComponent(map)}&limit=500`,{signal:controller.signal})
      .then(async (response) => { if (!response.ok) throw new Error(`HTTP ${response.status}`); return await response.json() as ApiPayload; })
      .then(async (payload) => {
        const shared=sharedIds(); const stored=savedIds(`trp-plan:${map}`);
        const share=new URLSearchParams(window.location.search).get("share");
        let cloudPlan:StoredPlan|null=null;
        try { const response=await fetch(share?`/api/plans?share=${encodeURIComponent(share)}`:`/api/plans?map=${encodeURIComponent(map)}`,{signal:controller.signal}); if(response.ok) cloudPlan=(await response.json()).plan; } catch { cloudPlan=null; }
        if(cloudPlan?.map&&cloudPlan.map!==map){setSyncReady(false);setLoading(true);setMap(cloudPlan.map);return}
        const restoredIds=cloudPlan?new Set(cloudPlan.selectedTaskIds):shared.size?shared:stored;
        let next:Task[] = (payload.data as ApiTask[]).flatMap((task,index) => task.objectives.filter((objective)=>objective.mapScope==="any"||objective.maps.some((entry)=>entry.name.toLowerCase()===map.toLowerCase())).map((objective,objectiveIndex)=>{
          const visual=position(objective.id,index+objectiveIndex);const world=objectivePoint(objective);const objectiveFloor=world?floorFor(world):"GROUND";const id=`${task.id}:${objective.id}`;
          return {id,sourceTaskId:task.id,title:task.name,trader:task.trader?.name ?? "Unknown",objective:objective.description,zone:objective.mapScope==="any"?"Any map":map,...visual,world,floor:objectiveFloor,status:objective.coordinateStatus==="unmapped"?"UNMAPPED" as const:objective.coordinateStatus==="verified"?"READY" as const:"VERIFY" as const,selected:pendingPartyObjectives.current.size?pendingPartyObjectives.current.has(objective.id):restoredIds.size?restoredIds.has(id):index<3,requirements:{minPlayerLevel:task.minPlayerLevel,prerequisiteTaskIds:task.prerequisiteTaskIds??[],objectives:[objective]}};
        }));
        const spawnSource=(payload.map?.spawns??[]).map((entry,index):SourceMarker|null=>{const point=worldPoint(entry.position);return point?{id:`spawn-${index}`,name:entry.zoneName??"SPAWN",point}:null}).filter((entry):entry is SourceMarker=>entry!==null).slice(0,16);
        const extractSource=(payload.map?.extracts??[]).map((entry):SourceMarker|null=>{const point=worldPoint(entry.position);return point?{id:entry.id,name:entry.name,point,meta:{faction:entry.faction,conditional:Boolean(entry.switches?.length)}}:null}).filter((entry):entry is SourceMarker=>entry!==null);
        const hazardSource=(payload.map?.hazards??[]).map((entry):SourceMarker|null=>{const point=worldPoint(entry.position);return point?{id:entry.id,name:entry.hazardType??entry.name??"HAZARD",point}:null}).filter((entry):entry is SourceMarker=>entry!==null);
        const lockSource=(payload.map?.locks??[]).map((entry):SourceMarker|null=>{const point=worldPoint(entry.position);return point?{id:entry.id,name:entry.needsPower?"POWER":entry.key?"KEY":"LOCK",point,meta:{keyId:entry.key,needsPower:entry.needsPower}}:null}).filter((entry):entry is SourceMarker=>entry!==null);
        const projectionBounds=boundsFor([...next.map((task)=>task.world),...spawnSource.map((entry)=>entry.point),...extractSource.map((entry)=>entry.point),...hazardSource.map((entry)=>entry.point),...lockSource.map((entry)=>entry.point)]);
        next=next.map((task)=>task.world?{...task,...projectPoint(task.world,projectionBounds)}:task);
        const marker=(entry:SourceMarker):TacticalMarker=>({...projectPoint(entry.point,projectionBounds),id:entry.id,name:entry.name,floor:floorFor(entry.point),world:entry.point,meta:entry.meta});
        const projectedSpawns=spawnSource.map(marker),projectedExtracts=extractSource.map(marker);
        setMarkers({spawns:projectedSpawns,extracts:projectedExtracts});setHazards(hazardSource.map(marker));setLocks(lockSource.map(marker));setSpawnId(projectedSpawns[0]?.id??"");setExtractId(projectedExtracts[0]?.id??"");
        if(cloudPlan?.routeTaskIds.length){const order=new Map(cloudPlan.routeTaskIds.map((id,index)=>[id,index]));next=[...next].sort((a,b)=>(order.get(a.id)??9999)-(order.get(b.id)??9999))}
        setTasks(next);pendingPartyObjectives.current.clear(); setChecklistState(cloudPlan?.checklistState??{});setAssignments(cloudPlan?.assignments??{});setTaskOwners(cloudPlan?.taskOwners??{});setShareId(cloudPlan?.shareId??""); revisionRef.current=cloudPlan?.revision??0; setRevision(revisionRef.current); setSquad(cloudPlan?.members??initialSquad); setOwnerUserId(cloudPlan?.ownerUserId??""); setCurrentUserId(cloudPlan?.currentUserId??""); setCanEdit(!share); setSyncMode(share?"SHARED":cloudPlan?"CLOUD":"LOCAL"); setSyncReady(true); setUpdatedAt(payload.meta?.fetchedAt ?? ""); setLoading(false);
      })
      .catch((reason) => { if (reason.name!=="AbortError") { setError("データを取得できませんでした。デモデータを表示しています。"); setTasks(initialTasks); setLoading(false); } });
    return () => controller.abort();
  },[map,gameMode]);

  useEffect(() => { const requested=new URLSearchParams(window.location.search).get("map"); if(!requested||!maps.includes(requested)) return; const timer=window.setTimeout(()=>{setSyncReady(false);setLoading(true);setMap(requested)},0); return ()=>window.clearTimeout(timer); },[]);
  useEffect(()=>{const local=localStorage.getItem("trp-profile");const timer=window.setTimeout(()=>{if(local){try{setProfile(JSON.parse(local) as PlayerProfile)}catch{/* use defaults */}}},0);fetch("/api/profile").then(async(response)=>response.ok?(await response.json()).profile:null).then((cloud)=>{if(cloud)setProfile(cloud);setProfileReady(true)}).catch(()=>setProfileReady(true));return()=>window.clearTimeout(timer)},[]);
  useEffect(()=>{if(!profileReady)return;localStorage.setItem("trp-profile",JSON.stringify(profile));const timer=window.setTimeout(()=>fetch("/api/profile",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(profile)}).catch(()=>undefined),600);return()=>window.clearTimeout(timer)},[profile,profileReady]);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/tarkov/tasks?lang=ja&mode=${gameMode}&limit=1000`,{signal:controller.signal}).then(async(response)=>response.ok?(await response.json() as ApiPayload):null).then((payload)=>{if(payload)setTaskCatalog(payload.data)}).catch(()=>undefined);return()=>controller.abort()},[gameMode]);
  useEffect(()=>{const timer=window.setTimeout(()=>{setProgressReady(false);const key=`trp-progress:${gameMode}`;try{const local=JSON.parse(localStorage.getItem(key)??"{}");setTaskStates(local.taskStates??{});setObjectiveStates(local.objectiveStates??{})}catch{setTaskStates({});setObjectiveStates({})}fetch(`/api/tasks/progress?mode=${gameMode}`).then(async(response)=>response.ok?(await response.json()).progress:null).then((progress)=>{if(progress){setTaskStates(progress.taskStates??{});setObjectiveStates(progress.objectiveStates??{})}setProgressReady(true)}).catch(()=>setProgressReady(true))},0);return()=>window.clearTimeout(timer)},[gameMode]);
  useEffect(()=>{if(!progressReady)return;const progress={taskStates,objectiveStates};localStorage.setItem(`trp-progress:${gameMode}`,JSON.stringify(progress));const timer=window.setTimeout(()=>fetch("/api/tasks/progress",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({mode:gameMode,...progress})}).catch(()=>undefined),600);return()=>window.clearTimeout(timer)},[gameMode,taskStates,objectiveStates,progressReady]);
  useEffect(()=>{const timer=window.setTimeout(()=>setShowWelcome(!localStorage.getItem("trp-onboarded")),0);return()=>window.clearTimeout(timer)},[]);
  useEffect(()=>{if(activeNav!=="Party")return;const timer=window.setTimeout(()=>{if(!shareId){setPartyProgress([{userId:currentUserId||"local-owner",displayName:squad[0]?.displayName??"LOCAL OWNER",color:colors[0],ready:squad[0]?.ready??false,taskStates,objectiveStates}]);return}fetch(`/api/plans/party?share=${encodeURIComponent(shareId)}&mode=${gameMode}`).then(async(response)=>response.ok?(await response.json()).members:null).then((members)=>{if(members)setPartyProgress(members)}).catch(()=>undefined)},800);return()=>window.clearTimeout(timer)},[activeNav,shareId,gameMode,revision,currentUserId,squad,taskStates,objectiveStates]);
  useEffect(() => { if(loading) return; localStorage.setItem(`trp-plan:${map}`,JSON.stringify(tasks.filter((task)=>task.selected).map((task)=>task.id))); const show=window.setTimeout(()=>setSaved(true),0); const hide=window.setTimeout(()=>setSaved(false),900); return ()=>{window.clearTimeout(show);window.clearTimeout(hide)}; },[tasks,loading,map]);
  useEffect(() => { if(applyingRemote.current){applyingRemote.current=false;return}if(!syncReady||(syncMode==="SHARED"&&!canEdit)) return; const timer=window.setTimeout(async()=>{const route=tasks.filter((task)=>task.selected).map((task)=>task.id);try{const response=await fetch("/api/plans",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({map,selectedTaskIds:route,routeTaskIds:route,checklistState,assignments,taskOwners,shareId:syncMode==="SHARED"?shareId:undefined,revision:revisionRef.current})});const payload=await response.json();if(response.ok){setShareId(payload.plan.shareId);revisionRef.current=payload.plan.revision;setRevision(revisionRef.current);setSquad(payload.plan.members);if(syncMode!=="SHARED")setSyncMode("CLOUD")}else if(response.status===409){setConflict(payload.plan)}}catch{if(syncMode!=="SHARED")setSyncMode("LOCAL")}},700);return()=>window.clearTimeout(timer)},[tasks,map,syncReady,syncMode,canEdit,shareId,checklistState,assignments,taskOwners]);
  useEffect(()=>{if(syncMode!=="SHARED"||!shareId)return;let stopped=false;let timer=0;const poll=async()=>{try{const response=await fetch(`/api/plans?share=${encodeURIComponent(shareId)}`);if(response.ok){const {plan}=await response.json() as {plan:StoredPlan};setSquad(plan.members);setOwnerUserId(plan.ownerUserId);setCurrentUserId(plan.currentUserId??"");if(plan.revision!==revisionRef.current){revisionRef.current=plan.revision;setRevision(plan.revision);setChecklistState(plan.checklistState);setAssignments(plan.assignments);setTaskOwners(plan.taskOwners??{});const order=new Map(plan.routeTaskIds.map((id,index)=>[id,index]));applyingRemote.current=true;setTasks((items)=>[...items.map((task)=>({...task,selected:plan.selectedTaskIds.includes(task.id)}))].sort((a,b)=>(order.get(a.id)??9999)-(order.get(b.id)??9999)))}}}catch{/* retry on the next adaptive interval */}finally{if(!stopped)timer=window.setTimeout(poll,document.hidden?10000:2000)}};timer=window.setTimeout(poll,2000);return()=>{stopped=true;window.clearTimeout(timer)}},[syncMode,shareId]);
  const joinSquad=async()=>{if(!shareId)return;const response=await fetch("/api/plans/join",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({shareId})});if(response.status===401){window.location.href=`/signin-with-chatgpt?return_to=${encodeURIComponent(window.location.pathname+window.location.search)}`;return}if(response.ok)setCanEdit(true)};
  const updateMember=async(body:Record<string,unknown>,method="PATCH")=>{const response=await fetch("/api/plans/join",{method,headers:{"content-type":"application/json"},body:JSON.stringify({shareId,...body})});if(response.ok&&"ready" in body)setSquad((members)=>members.map((member)=>member.userId===currentUserId?{...member,ready:Boolean(body.ready)}:member));};
  const useRemoteConflict=()=>{if(!conflict)return;revisionRef.current=conflict.revision;setRevision(conflict.revision);setSquad(conflict.members);setChecklistState(conflict.checklistState);setAssignments(conflict.assignments);setTaskOwners(conflict.taskOwners??{});const order=new Map(conflict.routeTaskIds.map((id,index)=>[id,index]));applyingRemote.current=true;setTasks((items)=>[...items.map((task)=>({...task,selected:conflict.selectedTaskIds.includes(task.id)}))].sort((a,b)=>(order.get(a.id)??9999)-(order.get(b.id)??9999)));setConflict(null)};
  const keepLocalConflict=()=>{if(!conflict)return;revisionRef.current=conflict.revision;setRevision(conflict.revision);setConflict(null);setTasks((items)=>[...items])};
  const toggleKey=(keyId?:string)=>{if(!keyId)return;setProfile((current)=>({...current,keyIds:current.keyIds.includes(keyId)?current.keyIds.filter((id)=>id!==keyId):[...current.keyIds,keyId]}))};

  return <main className="app-shell">
    <a className="skip-link" href="#main-content">メインコンテンツへ移動</a>
    {showWelcome&&<div className="welcome-overlay" role="presentation"><section className="welcome-dialog" role="dialog" aria-modal="true" aria-labelledby="welcome-title"><p className="eyebrow">TARKOV RAID PLANNERへようこそ</p><h2 id="welcome-title">レイド準備を、ひとつの画面で。</h2><div className="welcome-steps"><article><strong>01</strong><b>タスクを選ぶ</b><span>マイタスクで進行状況を登録します。</span></article><article><strong>02</strong><b>ルートを組む</b><span>レイド計画で目標と脱出口をまとめます。</span></article><article><strong>03</strong><b>分隊で共有</b><span>パーティーで担当と準備状況を揃えます。</span></article></div><button className="button primary" onClick={()=>{localStorage.setItem("trp-onboarded","1");setShowWelcome(false)}}>計画を始める</button></section></div>}
    <aside className="sidebar">
      <div className="brand" aria-label="Tarkov Raid Planner"><span className="brand-mark">TRP</span><span className="brand-copy">TARKOV<br/><b>RAID PLANNER</b></span></div>
      <nav aria-label="全体ナビゲーション">{[
        {value:"My tasks",label:"マイタスク",icon:"target"},{value:"Raid plan",label:"レイド計画",icon:"map"},{value:"Party",label:"パーティー",icon:"users"}
      ].map((item) => <button key={item.value} aria-current={activeNav===item.value?"page":undefined} className={activeNav===item.value?"nav-item active":"nav-item"} onClick={() => setActiveNav(item.value)}><Icon name={item.icon as "grid"}/><span>{item.label}</span>{item.value==="Raid plan"&&<i>{selected.length}</i>}</button>)}</nav>
      <div className="sidebar-foot"><a className="sync-auth" href={syncMode==="LOCAL"?"/signin-with-chatgpt?return_to=%2F":"/signout-with-chatgpt?return_to=%2F"}>{syncMode==="LOCAL"?"ログインして同期":"クラウド同期中"}</a><button aria-current={activeNav==="Settings"?"page":undefined} className={activeNav==="Settings"?"nav-item active":"nav-item"} onClick={()=>setActiveNav("Settings")}><Icon name="settings"/><span>設定</span></button><div className="profile"><span>G8</span><div><b>GO825</b><small>{syncMode==="LOCAL"?"端末保存":"クラウド保存"} · USEC</small></div><em>•••</em></div></div>
    </aside>

    <section id="main-content" className={`workspace ${activeNav==="My tasks"?"my-tasks-mode":""} ${activeNav==="Party"?"party-mode":""} ${activeNav==="Settings"?"settings-mode":""}`}>
      {activeNav==="Raid plan"&&<header className="topbar"><div><p className="eyebrow">作戦 / {map.toUpperCase()}</p><h1>レイド計画</h1></div><div className="top-actions">
        <label className="map-select"><span>マップ</span><select value={map} onChange={(event) => {setSyncReady(false);setLoading(true);setError("");setMap(event.target.value)}}>{maps.map((name) => <option key={name}>{name}</option>)}</select></label>
        <div className="mode-switch"><button className={mode==="PLAN"?"on":""} onClick={() => setMode("PLAN")}>計画</button><button className={mode==="LIVE"?"live on":"live"} onClick={() => setMode("LIVE")}>レイド中</button></div>
        <button className="button secondary" onClick={share}><Icon name="share"/>{copied?"コピー済み":"計画を共有"}</button><button className="button primary" onClick={newPlan}><Icon name="plus"/>新規計画</button>
      </div></header>}

      {error&&<div className="data-alert" role="status">{error}</div>}
      {conflict&&<div className="conflict-alert" role="alert"><div><b>分隊の計画が更新されました</b><span>別のメンバーが先に更新しました。使用する内容を選択してください。</span></div><button onClick={useRemoteConflict}>分隊版を使用</button><button onClick={keepLocalConflict}>自分の版を使用</button></div>}
      {activeNav==="Settings"&&<section className="settings-page"><div className="settings-head"><div><p className="eyebrow">アカウント・プライバシー・設定</p><h2>設定</h2></div>{settingsNotice&&<span role="status">{settingsNotice}</span>}</div><div className="settings-grid"><section className="setting-card panel"><h3>プレイ設定</h3><label>ゲームモード<select value={gameMode} onChange={(event)=>setGameMode(event.target.value as "regular"|"pve")}><option value="regular">PVP</option><option value="pve">PVE</option></select></label><label>レベル<input type="number" min="1" max="79" value={profile.playerLevel} onChange={(event)=>setProfile((current)=>({...current,playerLevel:Math.max(1,Math.min(79,Number(event.target.value)||1))}))}/></label><label>陣営<select value={profile.faction} onChange={(event)=>setProfile((current)=>({...current,faction:event.target.value as "pmc"|"scav"}))}><option value="pmc">PMC</option><option value="scav">SCAV</option></select></label></section><section className="setting-card panel"><h3>データ管理</h3><p>クラウド保存データはJSONで取得できます。端末データの削除はこのブラウザだけに作用します。</p><div className="setting-actions"><button className="button secondary" onClick={exportAccount}>データを書き出す</button><button className="button secondary" onClick={clearLocal}>この端末のデータを削除</button></div></section><section className="setting-card danger-card panel"><h3>アカウントデータ削除</h3><p>所有するプラン、参加情報、プロフィール、タスク進行を完全に削除します。取り消せません。</p><label>確認のため DELETE と入力<input value={deleteConfirm} onChange={(event)=>setDeleteConfirm(event.target.value)} placeholder="DELETE"/></label><button className="button danger" disabled={deleteConfirm!=="DELETE"} onClick={deleteAccount}>クラウドデータを削除</button></section><section className="setting-card panel"><h3>情報とポリシー</h3><div className="legal-links"><a href="/privacy">プライバシー</a><a href="/terms">利用規約</a><a href="/credits">クレジット・免責</a></div><button className="button secondary" onClick={()=>setShowWelcome(true)}>ガイドを表示</button></section></div></section>}
      {activeNav==="Party"&&<section className="party-dashboard"><div className="party-overview panel"><div className="party-head"><div><p className="eyebrow">分隊情報 · {gameMode.toUpperCase()}</p><h2>パーティー概要</h2></div><button className="button secondary" onClick={share}><Icon name="share"/>{copied?"コピー済み":"招待をコピー"}</button></div><div className="party-roster">{partyProgress.map((member)=>{const assigned=checklist.filter((item)=>assignments[item.id]===member.userId),done=assigned.filter((item)=>checklistState[item.id]).length;return <article key={member.userId}><i style={{background:member.color}}/><div><b>{member.displayName}</b><small>{Object.values(member.taskStates).filter((state)=>state==="active").length} 進行中タスク · {done}/{assigned.length} 装備準備</small></div><span className={member.ready&&done===assigned.length?"party-ready":"party-prep"}>{member.ready&&done===assigned.length?"準備完了":"準備中"}</span></article>})}</div></div><div className="party-columns"><section className="panel recommendations"><div className="party-section-head"><p className="eyebrow">効率ランキング</p><h2>おすすめレイド</h2></div>{partyDashboard.recommendations.map((entry,index)=><article key={entry.map}><strong>0{index+1}</strong><div><b>{entry.map}</b><small>{entry.objectiveCount} 目標 · {entry.memberCount} 人 · スコア {entry.score}</small></div><button disabled={entry.map==="Any map"} onClick={()=>createPartyPlan(entry)}>計画を作成</button></article>)}{!partyDashboard.recommendations.length&&<div className="party-empty">メンバーがマイタスクで「進行中」にしたタスクがありません。</div>}</section><section className="panel shared-objectives"><div className="party-section-head"><p className="eyebrow">目標ごとに統合</p><h2>共有目標</h2></div>{partyDashboard.groups.slice(0,40).map((group)=><article key={group.id}><div><small>{group.taskName} · {group.mapScope.toUpperCase()}</small><b>{group.description}</b></div><span>{group.owners.map((owner)=><i key={owner.userId} style={{background:owner.color}} title={owner.displayName}>{owner.displayName.slice(0,1).toUpperCase()}</i>)}</span></article>)}</section></div></section>}
      {activeNav==="My tasks"&&<section className="my-tasks panel"><div className="my-tasks-head"><div><p className="eyebrow">プレイヤー進行・手動管理</p><h2>マイタスク</h2></div><div className="mode-switch"><button className={gameMode==="regular"?"on":""} onClick={()=>setGameMode("regular")}>PVP</button><button className={gameMode==="pve"?"on":""} onClick={()=>setGameMode("pve")}>PVE</button></div></div><div className="task-filters">{(["all","available","active","completed","locked"] as const).map((filter)=><button key={filter} className={taskFilter===filter?"on":""} onClick={()=>setTaskFilter(filter)}>{taskFilterLabels[filter]}</button>)}<span>{filteredCatalog.length} 件</span></div><div className="progress-list">{filteredCatalog.map((task)=>{const locked=taskLocked(task);const state=taskStates[task.id]??"available";return <article className={locked?"progress-card locked":"progress-card"} key={task.id}><div className="progress-summary"><span>{locked?"未解放":taskProgressLabels[state]}</span><div><small>{task.trader?.name??"Unknown"} · レベル {task.minPlayerLevel}</small><h3>{task.name}</h3><p>{locked?`${task.minPlayerLevel>profile.playerLevel?`レベル ${task.minPlayerLevel} が必要です。 `:""}${task.prerequisiteTaskIds.filter((id)=>taskStates[id]!=="completed").length} 件の前提タスクが未完了です。`:`${task.objectives.length} 件の目標`}</p></div><select disabled={locked} value={state} onChange={(event)=>setTaskProgress(task,event.target.value as "available"|"active"|"completed")}><option value="available">受注可能</option><option value="active">進行中</option><option value="completed">完了</option></select></div><div className="objective-progress">{task.objectives.map((objective)=><div key={objective.id}><span>{objective.description}</span><small>{objective.mapScope.toUpperCase()} · {objective.type}</small><select disabled={locked||state!=="active"} value={objectiveStates[objective.id]??"pending"} onChange={(event)=>setObjectiveStates((current)=>({...current,[objective.id]:event.target.value as "pending"|"in_progress"|"completed"|"handover"}))}><option value="pending">未着手</option><option value="in_progress">進行中</option><option value="handover">引き渡し</option><option value="completed">完了</option></select></div>)}</div></article>})}</div></section>}
      <div className="planner-grid"><section className="map-panel panel"><div className="panel-head"><div><p className="eyebrow">戦術マップ・座標表示</p><h2>{map} ルート</h2></div><div className="map-view-tools"><div className="pan-tools"><button onClick={()=>setView((value)=>({...value,y:value.y+24}))}>↑</button><button onClick={()=>setView((value)=>({...value,x:value.x+24}))}>←</button><button onClick={()=>setView({zoom:1,x:0,y:0})}>●</button><button onClick={()=>setView((value)=>({...value,x:value.x-24}))}>→</button><button onClick={()=>setView((value)=>({...value,y:value.y-24}))}>↓</button><button onClick={()=>setView((value)=>({...value,zoom:Math.max(1,value.zoom-.25)}))}>−</button><b>{Math.round(view.zoom*100)}%</b><button onClick={()=>setView((value)=>({...value,zoom:Math.min(3,value.zoom+.25)}))}>＋</button></div><div className="floor-tools">{(["ALL","B1","GROUND","UPPER"] as const).map((level)=><button key={level} className={floor===level?"on":""} onClick={()=>setFloor(level)}>{floorLabels[level]}</button>)}</div></div></div>
        <div className="map-canvas" aria-label={`${map} tactical map`}><div className={mapAsset?"map-viewport has-map-art":"map-viewport"} style={{transform:`translate(${view.x}px,${view.y}px) scale(${view.zoom})`}}>{mapAsset&&<Image className="map-art" src={mapAsset} alt={`${map} コミュニティマップ`} fill unoptimized sizes="(max-width: 1050px) 100vw, 65vw"/>}<div className="terrain terrain-a"/><div className="terrain terrain-b"/><div className="terrain terrain-c"/><div className="road road-main"/><div className="road road-cross"/>
          <span className="zone-label z1">WEST</span><span className="zone-label z2">NORTH</span><span className="zone-label z3">SOUTH</span><span className="zone-label z4">EAST</span><svg className="route-svg" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={[chosenSpawn,...selected,chosenExtract].filter((entry):entry is TacticalMarker|Task=>Boolean(entry)&&(floor==="ALL"||entry.floor===floor)).map((entry)=>`${entry.x},${entry.y}`).join(" ")}/></svg>
          {hazards.filter((marker)=>floor==="ALL"||marker.floor===floor).map((marker)=><span key={marker.id} className="world-marker hazard-marker" style={{left:`${marker.x}%`,top:`${marker.y}%`}} title={marker.name}>!</span>)}
          {locks.filter((marker)=>floor==="ALL"||marker.floor===floor).slice(0,24).map((marker)=><button key={marker.id} className={lockAvailable(marker)?"world-marker lock-marker available":"world-marker lock-marker unavailable"} style={{left:`${marker.x}%`,top:`${marker.y}%`}} title={`${marker.name}: ${lockAvailable(marker)?"AVAILABLE":"MISSING REQUIREMENT"}`} onClick={()=>toggleKey(marker.meta?.keyId)}>K</button>)}
          {markers.spawns.filter((marker)=>floor==="ALL"||marker.floor===floor).slice(0,8).map((marker)=><button key={marker.id} className={marker.id===spawnId?"world-marker spawn-marker chosen":"world-marker spawn-marker"} style={{left:`${marker.x}%`,top:`${marker.y}%`}} title={`Spawn: ${marker.name}`} onClick={()=>setSpawnId(marker.id)}>S</button>)}
          {markers.extracts.filter((marker)=>floor==="ALL"||marker.floor===floor).map((marker)=><button key={marker.id} disabled={!extractAvailable(marker)} className={`${marker.id===extractId?"world-marker extract-marker chosen":"world-marker extract-marker"} ${extractAvailable(marker)?"available":"unavailable"}`} style={{left:`${marker.x}%`,top:`${marker.y}%`}} title={`Extract: ${marker.name} · ${extractAvailable(marker)?"AVAILABLE":"PROFILE BLOCKED"}`} onClick={()=>setExtractId(marker.id)}>E</button>)}
          {selected.filter((task)=>floor==="ALL"||task.floor===floor).map((task) => <button key={task.id} className="map-pin" style={{left:`${task.x}%`,top:`${task.y}%`,"--pin":taskColor(task)} as React.CSSProperties} title={`${task.title} · ${task.floor}`} onClick={()=>setActiveTask(task)}><span>{selected.findIndex((entry)=>entry.id===task.id)+1}</span><label>{task.title}<small>{task.floor}</small></label></button>)}
          <div className="map-legend"><span><i className="dot task-dot"/>目標</span><span><i className="dot spawn-dot"/>スポーン</span><span><i className="dot extract-dot"/>脱出口</span><span><i className="dot hazard-dot"/>危険地点</span><span><i className="dot lock-dot"/>鍵</span></div>
        </div>{activeTask&&<aside className="objective-detail"><button onClick={()=>setActiveTask(null)}>×</button><p className="eyebrow">{activeTask.trader} · {activeTask.zone}</p><h3>{activeTask.title}</h3><p>{activeTask.objective}</p><dl><div><dt>種類</dt><dd>{activeTask.requirements.objectives[0]?.type??"UNKNOWN"}</dd></div><div><dt>階層</dt><dd>{activeTask.floor}</dd></div><div><dt>対象マップ</dt><dd>{activeTask.requirements.objectives[0]?.mapScope??"UNKNOWN"}</dd></div><div><dt>前提タスク</dt><dd>{activeTask.requirements.prerequisiteTaskIds.length||"NONE"}</dd></div><div><dt>タスク所有者</dt><dd>{taskOwnerNames(activeTask.id)}</dd></div></dl></aside>}</div></section>
        <aside className="task-panel panel"><div className="panel-head"><div><p className="eyebrow">目標 · {syncMode} {saved&&"· 保存済み"}</p><h2>タスク一覧</h2></div><span className="task-count">{visibleTasks.length}</span></div><div className="task-search"><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="タスク・Trader・目標を検索" aria-label="タスク検索"/><span>⌕</span></div><div className="task-list">{visibleTasks.map((task) => <div key={task.id} className={task.selected?"task-card selected":"task-card"}><button className="task-main" onClick={() => toggleTask(task.id)}>
          <span className="task-index" style={{borderColor:task.color,color:task.color}}>{task.selected?selected.findIndex((t) => t.id===task.id)+1:"—"}</span><span className="task-copy"><small>{task.trader} · {task.zone}</small><b>{task.title}</b><em>{task.objective}</em></span><span className={`status ${task.status.toLowerCase()}`}>{requirementLabel(task.status)}</span><span className={task.selected?"check checked":"check"}>✓</span>
        </button>{task.selected&&<span className="route-order"><button onClick={()=>moveTask(task.id,-1)} aria-label={`${task.title}を前へ`}>↑</button><button onClick={()=>moveTask(task.id,1)} aria-label={`${task.title}を後へ`}>↓</button></span>}</div>)}{!loading&&visibleTasks.length===0&&<div className="empty-state">条件に一致するタスクはありません</div>}</div><button className="optimize" disabled={selected.length<2} onClick={optimizeRoute}><Icon name="route"/>ルートを最適化<span>↗</span></button></aside>
      </div>

      <section className="checklist-panel panel"><div className="checklist-head"><div><p className="eyebrow">装備・目標の必要条件</p><h2>レイド前チェックリスト</h2></div><strong>{completedChecklist}<span> / {checklist.length} 準備完了</span></strong></div><div className="checklist-body">{checklist.length?<div className="checklist-items">{checklist.map((item)=>{const done=Boolean(checklistState[item.id]);return <div className={done?"checklist-row done":"checklist-row"} key={item.id}><button aria-label={`${item.label}を完了`} onClick={()=>setChecklistState((state)=>({...state,[item.id]:!state[item.id]}))}>{done?"✓":""}</button><div><b>{item.label}</b><small>{item.taskTitle}{item.foundInRaid?" · レイド内で発見":""}{item.optional?" · 任意":""}</small></div><span className={`requirement-status ${(done?"ready":item.status).toLowerCase().replace(" ","-")}`}>{done?"準備済み":requirementLabel(item.status)}</span><select aria-label={`${item.label}の担当`} value={assignments[item.id]??""} onChange={(event)=>setAssignments((state)=>({...state,[item.id]:event.target.value}))}><option value="">未割り当て</option>{squad.map((member)=><option key={member.userId??member.displayName} value={member.userId??member.displayName}>{member.displayName}</option>)}</select></div>})}</div>:<div className="checklist-empty">タスクを選択すると必要な鍵・装備・レイド内行動を自動生成します。</div>}<aside className="readiness"><p className="eyebrow">分隊の準備状況</p>{squadReadiness.map((member)=><div key={member.userId??member.displayName}><span>{member.displayName}</span><b>{member.done}/{member.total}</b><i style={{width:`${member.total?member.done/member.total*100:0}%`}}/></div>)}</aside></div></section>

      <section className="squad-strip panel"><div className="squad-label"><p className="eyebrow">分隊 · 更新 {revision}</p><h2>分隊ステータス</h2></div>{squad.slice(0,3).map((member) => <div className="member" key={member.userId??member.displayName}><span className={member.ready?"avatar ready":"avatar"}>{member.displayName.split(/\s|@/).filter(Boolean).slice(0,2).map((part)=>part[0]).join("").toUpperCase()}</span><div><b>{member.displayName}</b>{isOwner&&member.userId!==ownerUserId?<select value={member.role} onChange={(event)=>updateMember({userId:member.userId,role:event.target.value})}><option value="MEMBER">メンバー</option><option value="SCOUT">偵察</option><option value="SUPPORT">支援</option></select>:<small>{member.role} · {member.lastSeenAt?"同期済み":"端末保存"}</small>}</div>{isOwner&&member.userId!==ownerUserId?<button className="member-remove" onClick={()=>updateMember({userId:member.userId},"DELETE")}>×</button>:<i className={member.ready?"signal online":"signal"}>{member.ready?"準備完了":"準備中"}</i>}</div>)}<div className="squad-actions">{currentMember&&<button className={currentMember.ready?"ready-toggle on":"ready-toggle"} onClick={()=>updateMember({ready:!currentMember.ready})}>{currentMember.ready?"READY":"準備完了にする"}</button>}<button className="invite" onClick={syncMode==="SHARED"&&!canEdit?joinSquad:share}><Icon name="plus"/>{syncMode==="SHARED"&&!canEdit?"参加":"招待"}</button></div></section>
      <footer><span>データ提供: TARKOV.DEV · {updatedAt?`更新 ${new Date(updatedAt).toLocaleString("ja-JP")}`:"ローカル代替データ"}</span><span><a href="/privacy">プライバシー</a> · <a href="/terms">利用規約</a> · <a href="/credits">クレジット</a> · 非公式 ESCAPE FROM TARKOV レイド計画ツール</span></footer>
    </section>
  </main>;
}
